version: "3"
services:
    node:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./:/usr/src/app
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: sa
            MYSQL_PASSWORD: Levanhieu1
    redis:
        image: redis:alpine
        container_name: redis
        ports:
        - '6379:6379'
        volumes:
        - redisDB:/data       
volumes:
    db-data: {}
    redisDB: