@url_dev=http://localhost:3000/v1/api
### sign's
GET http://localhost:3000/api

###
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "username": "fasa",
    "email": "levanhieu10",
    "password":"hieu1"
}
